sudo: false
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8

# Use gcc-4.8
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

compiler: gcc
language: c
script:
  - ./build.sh
